config/routes.rb
class SubdomainConstraint   
  def self.matches?(request)
    request.subdomain.present? && !ExcludedSubdomains.include?(request.subdomains.first)
  end 
end

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  constraints SubdomainConstraint do     
    root "features#index"
    resources :features, only: [:new, :create, :show] do
      resources :upvotes, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
  end

  root "dashboard#index"
  resources :products, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :feature
  belongs_to :product
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :user
  belongs_to :product

  has_many :upvotes
  has_many :comments

  validates :title, presence: true
  validates :description, presence: true

  enum status: { open: 0, review: 1, planned: 2, building: 3, released: 4, closed: 5 }

  def score
    #count = upvotes.loaded? ? upvotes.size : upvotes.count
    upvotes.size + id + 100
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :users
  has_many :features
  has_many :upvotes
  has_many :comments

  validates :name, presence: true
  validates :subdomain, uniqueness: { case_sensitive: false }, presence: true

  def self.current(subdomain)
    return unless subdomain
    return if ExcludedSubdomains.include? subdomain
    find_by_subdomain(subdomain)
  end

end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :feature
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :product, optional: true
  has_many :features
  has_many :upvotes
  has_many :comments

  def owns_product?
    return false unless product_id
    !!Product.find(product_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_product, :current_product_name

  def current_product
    @_current_product ||= Product.current(request.subdomains.first)
  end

  def current_product_name
    current_product ? current_product.name : "FeatureLoop"
  end

  def scope_to_product(attributes)
    attributes.merge(product_id: current_product.id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.new(scope_to_product(content: params[:comment][:content], feature_id: params[:feature_id]))
    if @comment.save
      flash[:success] = "Your comment has been added!"
    else
      flash[:error] = "Your comment could not be added."
    end
    redirect_to feature_path(@comment.feature)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    redirect_to new_product_path unless current_user.owns_product?
    # TODO: is this long term viable?
    redirect_to root_url(subdomain: current_user.product.subdomain)
  end

end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :ensure_product_tenant
  before_action :authenticate_user!, except: [:index, :show]

  layout "product_dashboard"

  def index
    @features = current_product.features.includes(:upvotes)
  end

  def new
    @feature = current_user.features.new
  end

  def create
    @feature = current_user.features.new(feature_params)
    if @feature.save
      flash[:success] = "Your feature request has been submitted!"
      redirect_to feature_path(@feature)
    else
      flash[:error] = "Your feature request could not be created. Please try again or contact support@featureloop.com for assistance."
      render :new
    end
  end

  def show
    @feature = current_product.features.find(params[:id])
  end

  private

  def ensure_product_tenant
    redirect_to root_path unless current_product
  end

  def feature_params
    scope_to_product(params.require(:feature).permit(:title, :description))
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      current_user.update(product_id: @product.id)
      redirect_to subdomain: @product.subdomain, controller: 'features', action: "index"
    else
      flash[:error] = "Your app could not be added. Please try again or contact support@featureloop.com for assistance."
      render :new
    end
  end

  def show
    @product = find_product_by_subdomain_or_id
    render :show, layout: "product_dashboard"
  end

  private

  def product_params
    params.require(:product).permit(:name, :subdomain)
  end

  def find_product_by_subdomain_or_id
    if tenant = Product.current(request.subdomains.first)
      Product.find_by_subdomain(tenant)
    else
      Product.find(params[:id])
    end
  end

end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :authenticate_user!

  def create
    if existing_upvote
      existing_upvote.destroy
    else
      @upvote = current_user.upvotes.create(scope_to_product(feature_id: params[:feature_id]))
    end
    redirect_to params[:return_url]
  end

  private

  def existing_upvote
    @_existing_upvote ||= current_user.upvotes.find_by_feature_id(params[:feature_id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.slim
h1 Products

app/views/features/index.html.slim
.page-header
  h1.page-header__heading Most Popular
  = link_to "Suggest a feature", new_feature_path, class: "page-header__cta"

- @features.sort_by(&:score).reverse.each do |feature|
  .card.card--feature
    .card-feature-summary
      = link_to feature_path(feature) do
        h4.u-mt--0 = feature.title
      p.u-mb--0 = feature.description.truncate(100)
    .card-feature-score
      .score-circle = feature.score
    .card-feature-upvote
      = link_to feature_upvotes_path(feature_id: feature.id, return_url: request.url), class: "upvote", method: :post do
        i.material-icons = "#{current_user&.upvotes&.where(feature_id: feature.id)&.present? ? 'keyboard_arrow_down' : 'keyboard_arrow_up'}"

app/views/features/new.html.slim
.row
  .col-md-8.col-md-offset-2
    .card.card--padding-lg
      h1.card__header.u-mb--0 New Feature Request
      p Have an idea that would make #{current_product.name} better? Fill out the form below!
      
      = bootstrap_form_for @feature, html: { class: "new_feature u-mt--2" } do |f|
        = f.text_field :title
        = f.text_area :description, rows: 10
        = f.submit "Submit", class: "button--primary"

app/views/features/show.html.slim
.row
  .col-md-8
    .card.card--padding-lg
      .row
        .col-xs-12
          h1.card__header.u-mb--0 = @feature.title
          p = "Submitted on #{@feature.created_at}"
          p class="feature-status feature-status--#{@feature.status.downcase}" = @feature.status.titleize
          p = @feature.description
      .row.u-mt--4
        .col-xs-12
          h4 = "Comments (#{@feature.comments.size})"
          - if @feature.comments.blank?
            em There are no comments yet.
          - else
            - @feature.comments.each do |comment|
              .u-mt--2.card.card--off-white
                .col-xs-12
                  = comment.content
                .col-xs-12.pull-right
                  = "Submitted by #{comment.user.email}"
                .clearfix
          hr

          h4 Leave a comment
          = bootstrap_form_for @feature.comments.new, url: feature_comments_path(feature_id: @feature.id) do |f|
            = f.text_area :content, hide_label: true
            = f.submit "Save comment", class: "button--primary"
  
  .col-md-4.text-center
    .score-circle.score-circle--big.u-mlr--auto.u-mt--4.u-mb--2 = @feature.score
    - if current_user&.upvotes&.where(feature_id: @feature.id)&.any?
      span.u-border--bottom.u-color--blue Thanks for supporting this feature!
    - else
      = link_to "+ Support this feature", feature_upvotes_path(feature_id: @feature.id, return_url: request.url), method: :post, class: "button button--primary"
    .u-mb--2

app/views/layouts/application.html.slim
doctype html
html
  head
    title = current_product_name
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700" rel="stylesheet"
  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to current_product_name, root_path, class: "navbar-brand"
        #navbar.collapse.navbar-collapse.pull-right
          ul.nav.navbar-nav
            - if current_user.present?
              li = link_to "Sign out", destroy_user_session_path, method: :delete
            - else
              li = link_to "Sign in", new_user_session_path
              li 
                p.navbar-btn
                  = link_to "Register", new_user_registration_path, class: "button--alt button--small"
    .container
      = yield

app/views/layouts/product_dashboard.html.slim
doctype html
html
  head
    title = "#{current_product&.name} Feature Requests"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700" rel="stylesheet"
  body
  nav.navbar.navbar-default.navbar-fixed-top
    .container
      .navbar-header
        button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to current_product.name, root_path, class: "navbar-brand"
      #navbar.collapse.navbar-collapse.pull-right
        ul.nav.navbar-nav
          - if current_user.present?
            li 
              = link_to "Sign out (#{current_user.username || current_user.email})", destroy_user_session_path, method: :delete
          - else
            li = link_to "Sign in", new_user_session_path
            li 
              p.navbar-btn
                = link_to "Register", new_user_registration_path, class: "button--alt button--small"
  .container
    = yield

app/views/products/new.html.slim
.card.card--md
  h1.card__header Start tracking feature requests for your app

  = bootstrap_form_for @product do |f|
    = f.text_field :name, label: "Product name", placeholder: "ex. Google"
    = f.text_field :subdomain, label: "Subdomain", placeholder: "ex. google", help: "This is how you and your customers will access your feature requests. Ex. https://google.featureloop.com"
    = f.submit "Start tracking feature requests!", class: "btn btn-primary"

app/views/products/show.html.slim
= link_to "Suggest a feature", "#"